//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODOANHTHU
    {
        public string MaBaoCaoDoanhThu { get; set; }
        public string MaDaiLy { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<double> TongDoanhThu { get; set; }
    
        public virtual DAILY DAILY { get; set; }
    }
}
