//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CHITIETHANGHOAXUAT: INotifyPropertyChanged
    {
        private string maPhieuXuat;
        public string MaPhieuXuat
        {
            get { return maPhieuXuat; }
            set
            {
                if (maPhieuXuat != value)
                {
                    maPhieuXuat = value;
                    RaisePropertyChanged("MaPhieuXuat");
                } } }

        private string maHangHoa;
        public string MaHangHoa
        {
            get { return maHangHoa; }
            set
            {
                if (MaHangHoa != value)
                {
                    maHangHoa = value;
                    RaisePropertyChanged("MaHangHoa");
                }
            }
        }

        private Nullable<int> soLuong;
        public Nullable<int> SoLuong
        {
            get { return soLuong; }
            set
            {
                if (soLuong !=value)
                {
                    soLuong = value;
                    RaisePropertyChanged("SoLuong");
                } } }

        public event PropertyChangedEventHandler PropertyChanged;
        private void RaisePropertyChanged(string property)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(property));
            }
        }

        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }


    }
}
