//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAILY()
        {
            this.BAOCAOCONGNOes = new HashSet<BAOCAOCONGNO>();
            this.BAOCAODOANHTHUs = new HashSet<BAOCAODOANHTHU>();
            this.DONHANGs = new HashSet<DONHANG>();
            this.NODAILies = new HashSet<NODAILY>();
            this.UUDAIs = new HashSet<UUDAI>();
        }
    
        public string MaDaiLy { get; set; }
        public string MaDinhMuc { get; set; }
        public string MaHopDong { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string CMND { get; set; }
        public string HoTenChuDaiLy { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string CapDaiLy { get; set; }
        public string TenDaiLy { get; set; }
        public string NoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOCONGNO> BAOCAOCONGNOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAODOANHTHU> BAOCAODOANHTHUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NODAILY> NODAILies { get; set; }
        public virtual DINHMUC DINHMUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UUDAI> UUDAIs { get; set; }
    }
}
