//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DONHANG:INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }

        private string maDonHang;
        public string MaDonHang
        {
            get { return maDonHang; }
            set
            {
                if (maDonHang!=value)
                {
                    maDonHang = value;
                    RaisePropertyChanged("MaDonHang");
                } } }


        private string maDaiLy;
        public string MaDaiLy
        {
            get { return maDaiLy; }
            set
            {
                if (maDaiLy != value)
                {
                    maDaiLy = value;
                    RaisePropertyChanged("MaDaiLy");
                }
            }
        }

        private Nullable<DateTime> ngayDangKy;
        public Nullable<System.DateTime> NgayDangKy
        {
            get { return ngayDangKy; }
            set
            {
                if (ngayDangKy!=value)
                {
                    ngayDangKy = value;
                    RaisePropertyChanged("NgayDangKy");
                }
            } }

        public event PropertyChangedEventHandler PropertyChanged;
        private void RaisePropertyChanged(string property)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(property));
            }
        }

        public virtual DAILY DAILY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
