//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.CHITIETHANGHOAXUATs = new HashSet<CHITIETHANGHOAXUAT>();
        }

        private string maHangHoa;
        public string MaHangHoa { get { return maHangHoa; } set
            {
                if (maHangHoa!= value)
                {
                    maHangHoa = value;
                }
            } }

        private string tenMatHang;
        public string TenMatHang { get { return tenMatHang; } set
            {
                if (tenMatHang != value)
                {
                    tenMatHang = value;
                }
            } }

        private Nullable<int> donGia;
        public Nullable<int> DonGia { get { return donGia; } set {
                if (donGia != value)
                {
                    donGia = value;
                }
            } }

        private Nullable<int> soLuongCon;
        public Nullable<int> SoLuongCon { get { return soLuongCon; } set {
                if (soLuongCon!=value)
                {
                    soLuongCon = value;
                }
            } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHANGHOAXUAT> CHITIETHANGHOAXUATs { get; set; }
    }
}
