//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HOADON:INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.PHIEUTHUs = new HashSet<PHIEUTHU>();
        }

        private string maHoaDon;
        public string MaHoaDon
        {
            get { return maHoaDon; }
            set
            {
                if (maHoaDon!=value)
                {
                    maHoaDon = value;
                    RaisePropertyChanged("MaHoaDon");
                } } }


        private string maDonHang;
        public string MaDonHang
        {
            get { return maDonHang; }
            set
            {
                if (maDonHang!=value)
                {
                    maDonHang = value;
                    RaisePropertyChanged("MaDonHang");
                }
            } }

        private string maPhieuXuat;
        public string MaPhieuXuat
        {
            get { return maPhieuXuat; }
            set
            {
                if (maPhieuXuat!=value)
                {
                    maPhieuXuat = value;
                    RaisePropertyChanged("MaPhieuXuat");
                }
            } }

        private Nullable<DateTime> ngayLap;
        public Nullable<System.DateTime> NgayLap
        {
            get { return ngayLap; }
            set
            {
                if (ngayLap!= value)
                {
                    ngayLap = value;
                    RaisePropertyChanged("NgayLap");
                }
            } }

        private Nullable<double> thanhTien;
        public Nullable<double> ThanhTien
        {
            get { return thanhTien; }
            set
            {
                if (thanhTien!=value)
                {
                    thanhTien = value;
                    RaisePropertyChanged("ThanhTien");
                } } }

        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string property)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(property));
            }
        }

        public virtual DONHANG DONHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHU> PHIEUTHUs { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
    }
}
