//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class NODAILY
    {
        public string MaNoDaiLy { get; set; }
        public string MaDaiLy { get; set; }
        public string MaPhieuThu { get; set; }
        public Nullable<double> TienNo { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        public virtual PHIEUTHU PHIEUTHU { get; set; }
    }
}
