//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PHIEUXUAT:INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUXUAT()
        {
            this.CHITIETHANGHOAXUATs = new HashSet<CHITIETHANGHOAXUAT>();
            this.HOADONs = new HashSet<HOADON>();
        }

        private string maPhieuXuat;
        public string MaPhieuXuat
        {
            get { return maPhieuXuat; }
            set
            {
                if (maPhieuXuat != value)
                {
                    maPhieuXuat = value;
                    RaisePropertyChanged("MaPhieuXuat");
                }
            } }

        private Nullable<DateTime> ngayXuat;
        public Nullable<System.DateTime> NgayXuat
        {
            get { return ngayXuat; }
            set
            {
                if (ngayXuat != value)
                {
                    ngayXuat = value;
                    RaisePropertyChanged("NgayXuat");
                }
            } }

        private Nullable<double> thanhTien;
        public Nullable<double> ThanhTien
        {
            get { return thanhTien; }
            set
            {
                if (thanhTien!=value)
                {
                    thanhTien = value;
                    RaisePropertyChanged("ThanhTien");
                }
            } }

        public event PropertyChangedEventHandler PropertyChanged;
        private void RaisePropertyChanged(string property)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(property));
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHANGHOAXUAT> CHITIETHANGHOAXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
