//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class UUDAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UUDAI()
        {
            this.DAILies = new HashSet<DAILY>();
        }

        private string maUuDai;
        public string MaUuDai
        {
            get { return maUuDai; }
            set
            {
                if (maUuDai!=value)
                {
                    maUuDai = value;
                }
            } }


        private string tenUuDai;
        public string TenUuDai
        {
            get { return tenUuDai; }
            set
            {
                if (tenUuDai != value)
                { 
                    tenUuDai = value;
                }
            }
        }

        private Nullable<DateTime> ngayBatDau;
        public Nullable<System.DateTime> NgayBatDau
        {
            get { return ngayBatDau; }
            set
            {
                if (ngayBatDau!=value)
                {
                    ngayBatDau = value;
                } } }


        private Nullable<DateTime> ngayKetThuc;

        public Nullable<System.DateTime> NgayKetThuc
        {
            get { return ngayKetThuc; }
            set
            {
                if (ngayKetThuc != value)
                {
                    ngayKetThuc = value;
                }
            }
        }

        private string capDaiLy;
        public string CapDaiLy
        {
            get { return capDaiLy; }
            set
            {
                if (capDaiLy!=value)
                {
                    capDaiLy = value;
                }
            } }

        private Nullable<double> phanTram;
        public Nullable<double> PhanTram
        {
            get { return phanTram; } set
            {
                if (phanTram!=value)
                {
                    phanTram = value;
                }
            } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAILY> DAILies { get; set; }
    }
}
